//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eatSUMthing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int ID { get; set; }
        public string Név { get; set; }
        public Nullable<System.DateTime> Születési_idő { get; set; }
        public string Anyja_neve { get; set; }
        public string Lakcím { get; set; }
        public string Státusz { get; set; }
        public string Intézmény { get; set; }
        public string Osztály { get; set; }
        public Nullable<bool> Tartós_beteg { get; set; }
        public Nullable<bool> Nagycsaládos { get; set; }
        public Nullable<bool> GYVK { get; set; }
        public Nullable<bool> Diétás { get; set; }
    }
}
